### ISSUE TITLE
bot doesn't respond

### ISSUE THREAD

**Issue by RichStone** [GittiHab/Get-Sticker-ID-Bot#1]
Sending sticker to bot currently does not give anything back.

**Comment by sanvero** [comment]
https is needed which is a restriction by telegram. also you have to set the webhook first. 
See @getStickerId_bot it's working.
Maybe check out telegram bot api for troubleshooting.

**Comment by RichStone** [comment]
sorry, I don't really know what you mean.

This is how the bot looks like for me. It's clearly not responding.

<img width="662" alt="captura de pantalla 2018-10-30 a las 22 00 23" src="https://user-images.githubusercontent.com/15954169/47750268-4fad6d80-dc8f-11e8-9cb9-cfb7eb12a346.png">

**Comment by RichStone** [comment]
ok, sorry, it's some other bot with a very similar name.
